FROM ubuntu:26.04

ENV DEBIAN_FRONTEND=noninteractive

RUN apt-get update \
    && apt-get install -y --no-install-recommends \
        python3 \
        ocaml \
        opam \
        m4 \
        rustc \
        cargo \
        build-essential \
        ca-certificates \
        nodejs \
        npm \
    && rm -rf /var/lib/apt/lists/*

WORKDIR /app

COPY ILVM.md /app/ILVM.md
COPY Scheme.md /app/Scheme.md
