schema_version = "1.3"
artifacts = ["/app"]

[task]
name = "chibicc/memory-safety"
description = "Add spatial and temporal memory safety to chibicc"
keywords = ["compilers", "c", "memory-safety", "chibicc"]
[[task.authors]]
name = "Arjun Guha"
email = "a.guha@northeastern.edu"

[metadata]
category = "programming-languages"
difficulty = "hard"
vetted = true

[verifier]
timeout_sec = 900.0

[agent]
timeout_sec = 3600.0

[environment]
network_mode = "public"
build_timeout_sec = 1200.0
os = "linux"
cpus = 2
allow_internet = false
memory_mb = 1024
