schema_version = "1.3"
artifacts = []

[task]
name = "nuprl/netkat-equivalence"
description = "Decide equivalence of history-sensitive NetKAT programs"
keywords = ["programming-languages", "netkat", "coalgebra", "automata", "bisimulation", "equivalence"]

[[task.authors]]
name = "Arjun Guha"
email = "a.guha@northeastern.edu"

[metadata]
category = "programming-languages"
difficulty = "hard"

[verifier]
timeout_sec = 900.0

[agent]
timeout_sec = 3600.0

[environment]
network_mode = "public"
build_timeout_sec = 900.0
os = "linux"
cpus = 4
allow_internet = true
memory_mb = 8192
