(define (classify n)
  (cond ((< n 0) 'negative)
        ((= n 0) 'zero)
        (else 'positive)))

(display (let ((xs (list 1 2 3))
               (text (string-append "tail" "-calls")))
           (list (classify (- 0 4))
                 (and (pair? xs) (= (length xs) 3))
                 (or #f text))))
(display "\n")
